name: Build Docs

on: [push, workflow_dispatch]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      path_to_doc: docs/_build/html

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Build docs
        run: uvx nox -s docs

      - name: Upload docs build as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ github.event.repository.name }}_docs
          path: ${{ github.workspace }}/${{ env.path_to_doc }}

      - name: Upload to github pages
        # only publish doc changes from main branch
        if: github.ref == 'refs/heads/main' && github.repository == 'cpp-linter/cpp-linter'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ env.path_to_doc }}
