name: PR Autolabeler

on:
  # pull_request event is required for autolabeler
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  draft-release:
    permissions:
      contents: write
      pull-requests: write
    uses: cpp-linter/.github/.github/workflows/release-drafter.yml@main
