name: PR Autolabeler

on:
  pull_request:
    branches: [main]

permissions: {}

jobs:
  # Auto label PRs during a PR event
  auto-label:
    permissions:
      contents: read
      pull-requests: write
    uses: cpp-linter/.github/.github/workflows/labeler.yml@tag-release
