name: Autolabeler

on:
  # pull_request_target event is required for autolabeler
  pull_request_target:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  draft-release:
    uses: cpp-linter/.github/.github/workflows/release-drafter.yml@main
