name: Release Drafter

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions: {}

jobs:
  draft-release:
    permissions:
      contents: write
    uses: cpp-linter/.github/.github/workflows/release-drafter.yml@main
