name: Summarize unreleased changes

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions: {}

jobs:
  # Auto label PRs during a PR event
  git-cliff:
    permissions:
      contents: read
      pull-requests: read
    uses: cpp-linter/.github/.github/workflows/unreleased-summary.yml@tag-release
